version: '3.8'

services:
  web:
    build: .
    container_name: ci3-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: ci3-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ci3_database
      MYSQL_USER: ci3_user
      MYSQL_PASSWORD: ci3_password
    ports:
      - "3306:3306"
